/* Generated by scripts/bundle-content.mjs. Do not edit. */
"use strict";
(() => {
/* ---- lib/settings.js ---- */
/** Default settings mirroring Firefox Picture-in-Picture prefs. */
const DEFAULT_SETTINGS = Object.freeze({
  toggleEnabled: true,
  alwaysShowToggle: false,
  minVideoSecs: 45,
  minVideoDimension: 140,
  respectDisablePictureInPicture: true,
  autoPipOnTabSwitch: false,
  keyboardControlsEnabled: true,
  captionsEnabled: true,
  captionFontSize: "medium",
  pauseOnClose: true,
  showPlaceholder: true,
});

const STORAGE_KEY = "pipAddonSettings";

function mergeSettings(partial) {
  return {
    ...DEFAULT_SETTINGS,
    ...(partial && typeof partial === "object" ? partial : {}),
  };
}

async function loadSettings() {
  if (typeof chrome !== "undefined" && chrome.storage?.sync) {
    const data = await chrome.storage.sync.get(STORAGE_KEY);
    return mergeSettings(data[STORAGE_KEY]);
  }
  return { ...DEFAULT_SETTINGS };
}

async function saveSettings(settings) {
  const next = mergeSettings(settings);
  if (typeof chrome !== "undefined" && chrome.storage?.sync) {
    await chrome.storage.sync.set({ [STORAGE_KEY]: next });
  }
  return next;
}

/* ---- lib/format.js ---- */
/**
 * Format a media timestamp the way Firefox PiP does:
 * M:SS or H:MM:SS, with an optional live fallback.
 */
function formatClock(seconds) {
  if (!Number.isFinite(seconds) || seconds < 0) {
    return "0:00";
  }
  const total = Math.floor(seconds);
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const secs = total % 60;
  const pad = (n) => String(n).padStart(2, "0");
  if (hours > 0) {
    return `${hours}:${pad(minutes)}:${pad(secs)}`;
  }
  return `${minutes}:${pad(secs)}`;
}

function formatTimestamp(currentTime, duration) {
  const live = !Number.isFinite(duration) || duration === Number.POSITIVE_INFINITY;
  if (live) {
    return `${formatClock(currentTime)} / LIVE`;
  }
  return `${formatClock(currentTime)} / ${formatClock(duration)}`;
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function progressRatio(currentTime, duration) {
  if (!Number.isFinite(duration) || duration <= 0) {
    return 0;
  }
  return clamp(currentTime / duration, 0, 1);
}

/* ---- lib/captions.js ---- */
const CAPTION_SELECTORS = [
  ".ytp-caption-segment",
  ".ytp-caption-window-container",
  ".caption-window",
  ".vp-captions",
  ".vjs-text-track-display",
];

function isCaptionTrack(track) {
  return track && (track.kind === "subtitles" || track.kind === "captions");
}

function listCaptionTracks(video) {
  if (!video?.textTracks) {
    return [];
  }
  return [...video.textTracks].filter(isCaptionTrack);
}

function activeCueText(track) {
  if (!track?.activeCues) {
    return "";
  }
  return [...track.activeCues]
    .map((cue) => cue.text)
    .filter(Boolean)
    .join("\n");
}

function showingCaptionText(video) {
  for (const track of listCaptionTracks(video)) {
    if (track.mode === "showing") {
      const text = activeCueText(track);
      if (text) {
        return text;
      }
    }
  }
  return "";
}

function pageCaptionText(root = document) {
  for (const selector of CAPTION_SELECTORS) {
    const nodes = root.querySelectorAll?.(selector);
    if (!nodes?.length) {
      continue;
    }
    const text = [...nodes]
      .map((node) => node.textContent?.trim())
      .filter(Boolean)
      .join("\n");
    if (text) {
      return text;
    }
  }
  return "";
}

function captionFontScale(size) {
  switch (size) {
    case "small":
      return 0.8;
    case "large":
      return 1.35;
    default:
      return 1;
  }
}

/* ---- lib/video-utils.js ---- */
const MIN_VIDEO_DIMENSION = 140;
const DEFAULT_MIN_VIDEO_SECS = 45;

/**
 * Firefox videocontrols.js shouldShowPictureInPictureToggle heuristics.
 * Audio is no longer required in current Firefox; duration + size are.
 */
function shouldShowPictureInPictureToggle(video, settings, dimensions) {
  if (!video) {
    return false;
  }
  if (settings.respectDisablePictureInPicture && video.disablePictureInPicture) {
    return false;
  }
  if (settings.alwaysShowToggle) {
    return true;
  }
  const duration = video.duration;
  if (Number.isNaN(duration)) {
    return false;
  }
  const minSecs = Number.isFinite(settings.minVideoSecs)
    ? settings.minVideoSecs
    : DEFAULT_MIN_VIDEO_SECS;
  if (Number.isFinite(duration) && duration < minSecs) {
    return false;
  }
  const width = dimensions?.videoWidth ?? video.clientWidth ?? 0;
  const height = dimensions?.videoHeight ?? video.clientHeight ?? 0;
  const minDim = Number.isFinite(settings.minVideoDimension)
    ? settings.minVideoDimension
    : MIN_VIDEO_DIMENSION;
  if (width < minDim || height < minDim) {
    return false;
  }
  return true;
}

function isLiveStream(video) {
  return !Number.isFinite(video?.duration) || video.duration === Number.POSITIVE_INFINITY;
}

function visibleArea(rect, viewportWidth, viewportHeight) {
  const left = Math.max(rect.left, 0);
  const top = Math.max(rect.top, 0);
  const right = Math.min(rect.right, viewportWidth);
  const bottom = Math.min(rect.bottom, viewportHeight);
  return Math.max(0, right - left) * Math.max(0, bottom - top);
}

/**
 * Pick the most relevant video, matching Firefox Ctrl+Shift+] behavior:
 * prefer a playing, on-screen video, then the largest visible one.
 */
function scoreVideo(video, viewport = { width: 1920, height: 1080 }) {
  if (!video) {
    return -1;
  }
  const rect = video.getBoundingClientRect?.() ?? {
    left: 0,
    top: 0,
    right: video.clientWidth || 0,
    bottom: video.clientHeight || 0,
    width: video.clientWidth || 0,
    height: video.clientHeight || 0,
  };
  const visible = visibleArea(rect, viewport.width, viewport.height);
  const area = Math.max(0, rect.width) * Math.max(0, rect.height);
  let score = visible + area * 0.05;
  if (!video.paused && !video.ended) {
    score += 1_000_000_000;
  }
  if ((video.readyState ?? 0) >= 2) {
    score += 1_000_000;
  }
  if (video.disablePictureInPicture) {
    score -= 500_000;
  }
  return score;
}

function pickBestVideo(videos, viewport) {
  let best = null;
  let bestScore = -1;
  for (const video of videos) {
    const score = scoreVideo(video, viewport);
    if (score > bestScore) {
      best = video;
      bestScore = score;
    }
  }
  return best;
}

function collectVideos(root = document, into = []) {
  if (!root) {
    return into;
  }
  const list =
    root.querySelectorAll?.("video") ??
    root.getElementsByTagName?.("video") ??
    [];
  for (const video of list) {
    into.push(video);
  }
  const walkRoot = root.body ?? root;
  const tree = walkRoot?.querySelectorAll?.("*") ?? [];
  for (const el of tree) {
    if (el.shadowRoot) {
      collectVideos(el.shadowRoot, into);
    }
  }
  return into;
}

/** Longest edge of a newly opened Document PiP window, in CSS pixels. */
const PIP_MAX_EDGE = 480;

function videoContentSize(video, stream) {
  const track = stream?.getVideoTracks?.()?.[0];
  const settings = typeof track?.getSettings === "function" ? track.getSettings() : {};
  const width =
    Number(settings.width) ||
    Number(video?.videoWidth) ||
    Number(video?.width) ||
    Number(video?.clientWidth) ||
    640;
  const height =
    Number(settings.height) ||
    Number(video?.videoHeight) ||
    Number(video?.height) ||
    Number(video?.clientHeight) ||
    360;
  return {
    width,
    height,
    ratio: width / height || 16 / 9,
  };
}

function fitSizeToBox(ratio, maxWidth, maxHeight) {
  const safeRatio = ratio > 0 && Number.isFinite(ratio) ? ratio : 16 / 9;
  let width = maxWidth;
  let height = width / safeRatio;
  if (height > maxHeight) {
    height = maxHeight;
    width = height * safeRatio;
  }
  return {
    width: Math.max(1, Math.round(width)),
    height: Math.max(1, Math.round(height)),
  };
}

/**
 * Size the Document PiP viewport to the video's real aspect ratio.
 * The old 480×270 box forced portrait/ultrawide clips into a 16:9 hole,
 * which Chrome then clamped — so the player either letterboxed or clipped.
 */
function pipWindowSize(video, maxWidth = PIP_MAX_EDGE, maxHeight = PIP_MAX_EDGE, stream) {
  const { ratio } = videoContentSize(video, stream);
  return fitSizeToBox(ratio, maxWidth, maxHeight);
}

function pipRequestOptions(video, stream) {
  const size = pipWindowSize(video, PIP_MAX_EDGE, PIP_MAX_EDGE, stream);
  return {
    width: size.width,
    height: size.height,
    preferInitialWindowPlacement: true,
  };
}

function windowChromeSize(win) {
  if (!win) {
    return { width: 0, height: 0 };
  }
  return {
    width: Math.max(0, (Number(win.outerWidth) || 0) - (Number(win.innerWidth) || 0)),
    height: Math.max(0, (Number(win.outerHeight) || 0) - (Number(win.innerHeight) || 0)),
  };
}

function outerSizeForInner(win, innerWidth, innerHeight) {
  const chrome = windowChromeSize(win);
  return {
    width: Math.round(innerWidth + chrome.width),
    height: Math.round(innerHeight + chrome.height),
  };
}

function aspectMismatch(width, height, ratio, epsilon = 0.02) {
  if (!width || !height || !ratio) {
    return true;
  }
  return Math.abs(width / height - ratio) > epsilon;
}

/** Grow the short side of a viewport so it matches `ratio` without shrinking the video. */
function growInnerToAspect(innerWidth, innerHeight, ratio) {
  const safeRatio = ratio > 0 && Number.isFinite(ratio) ? ratio : 16 / 9;
  const current = innerWidth / innerHeight || safeRatio;
  if (current > safeRatio) {
    return {
      width: Math.round(innerWidth),
      height: Math.round(innerWidth / safeRatio),
    };
  }
  return {
    width: Math.round(innerHeight * safeRatio),
    height: Math.round(innerHeight),
  };
}

/** Keep the edge the user dragged; adjust the other so the ratio stays locked. */
function snapInnerToAspect(innerWidth, innerHeight, ratio, previous) {
  const safeRatio = ratio > 0 && Number.isFinite(ratio) ? ratio : 16 / 9;
  if (!previous) {
    return growInnerToAspect(innerWidth, innerHeight, safeRatio);
  }
  const deltaWidth = Math.abs(innerWidth - previous.width);
  const deltaHeight = Math.abs(innerHeight - previous.height);
  if (deltaWidth >= deltaHeight) {
    return {
      width: Math.round(innerWidth),
      height: Math.round(innerWidth / safeRatio),
    };
  }
  return {
    width: Math.round(innerHeight * safeRatio),
    height: Math.round(innerHeight),
  };
}

/* ---- lib/remote-video.js ---- */
function snapshotVideo(video, title = "") {
  return {
    title,
    paused: Boolean(video.paused),
    ended: Boolean(video.ended),
    currentTime: Number(video.currentTime) || 0,
    duration: Number.isFinite(video.duration) ? video.duration : null,
    volume: Number.isFinite(video.volume) ? video.volume : 1,
    muted: Boolean(video.muted),
    playbackRate: Number(video.playbackRate) || 1,
    readyState: Number(video.readyState) || 0,
    videoWidth: Number(video.videoWidth) || Number(video.clientWidth) || 640,
    videoHeight: Number(video.videoHeight) || Number(video.clientHeight) || 360,
  };
}

async function preserveVideoQuality(track, sender) {
  track.contentHint = "detail";
  const parameters = sender.getParameters();
  parameters.degradationPreference = "maintain-resolution";
  for (const encoding of parameters.encodings) {
    encoding.scaleResolutionDownBy = 1;
    encoding.maxBitrate = 20_000_000;
  }
  await sender.setParameters(parameters);
}

class RemoteVideo extends EventTarget {
  constructor(stream, state, send) {
    super();
    this.stream = stream;
    this.state = {};
    this.send = send;
    this.disablePictureInPicture = false;
    this.textTracks = [];
    this.update(state);
  }

  update(state) {
    Object.assign(this.state, state, {
      duration: state?.duration == null ? Number.POSITIVE_INFINITY : state.duration,
    });
    this.dispatchEvent(new Event("timeupdate"));
  }

  command(name, value) {
    this.send?.({ name, value });
    this.dispatchEvent(new Event("timeupdate"));
  }

  captureStream() {
    return this.stream;
  }

  play() {
    this.state.paused = false;
    this.state.ended = false;
    this.command("play");
    return Promise.resolve();
  }

  pause() {
    this.state.paused = true;
    this.command("pause");
  }

  get title() { return this.state.title || ""; }
  get paused() { return this.state.paused; }
  get ended() { return this.state.ended; }
  get duration() { return this.state.duration; }
  get readyState() { return this.state.readyState; }
  get videoWidth() { return this.state.videoWidth; }
  get videoHeight() { return this.state.videoHeight; }
  get clientWidth() { return this.state.videoWidth; }
  get clientHeight() { return this.state.videoHeight; }

  get currentTime() { return this.state.currentTime; }
  set currentTime(value) {
    this.state.currentTime = Number(value) || 0;
    this.command("currentTime", this.state.currentTime);
  }

  get volume() { return this.state.volume; }
  set volume(value) {
    this.state.volume = Number(value);
    this.command("volume", this.state.volume);
  }

  get muted() { return this.state.muted; }
  set muted(value) {
    this.state.muted = Boolean(value);
    this.command("muted", this.state.muted);
  }

  get playbackRate() { return this.state.playbackRate; }
  set playbackRate(value) {
    this.state.playbackRate = Number(value) || 1;
    this.command("playbackRate", this.state.playbackRate);
  }
}

/* ---- lib/keys.js ---- */
const SEEK_TIME_SECS = 5;
const VOLUME_STEP = 0.1;

function isMacPlatform(platform = "") {
  return /Mac|iPhone|iPad|iPod/i.test(platform);
}

/**
 * Build the Firefox PictureInPictureChild keystroke token.
 * Accel is Meta on macOS and Ctrl elsewhere.
 */
function buildKeystroke({
  altKey = false,
  shiftKey = false,
  metaKey = false,
  ctrlKey = false,
  key = "",
  platform = "",
} = {}) {
  let keystroke = "";
  if (altKey) {
    keystroke += "alt-";
  }
  if (shiftKey) {
    keystroke += "shift-";
  }
  const mac = isMacPlatform(platform);
  if (mac) {
    if (metaKey) {
      keystroke += "accel-";
    }
    if (ctrlKey) {
      keystroke += "control-";
    }
  } else {
    if (metaKey) {
      keystroke += "meta-";
    }
    if (ctrlKey) {
      keystroke += "accel-";
    }
  }

  const map = {
    ArrowUp: "upArrow",
    ArrowDown: "downArrow",
    ArrowLeft: "leftArrow",
    ArrowRight: "rightArrow",
    Home: "home",
    End: "end",
    " ": "space",
    Spacebar: "space",
    w: "w",
    W: "w",
    f: "f",
    F: "f",
    Escape: "escape",
  };
  const token = map[key];
  if (!token) {
    return keystroke;
  }
  return keystroke + token;
}

function roundedVolume(value) {
  return Math.round(clamp(value, 0, 1) * 100) / 100;
}

function applyKeystroke(video, keystroke, options = {}) {
  if (!video) {
    return { action: "none" };
  }
  const live = options.isLive === true;
  const pauseOnClose = options.pauseOnClose !== false;

  switch (keystroke) {
    case "space": {
      if (video.paused || video.ended) {
        video.play?.();
        return { action: "play" };
      }
      video.pause?.();
      return { action: "pause" };
    }
    case "accel-w": {
      if (pauseOnClose) {
        video.pause?.();
      }
      return { action: "close", pause: pauseOnClose };
    }
    case "shift-escape": {
      return { action: "close", pause: false };
    }
    case "escape": {
      if (options.isFullscreen) {
        return { action: "exit-fullscreen" };
      }
      if (pauseOnClose) {
        video.pause?.();
      }
      return { action: "close", pause: pauseOnClose };
    }
    case "f": {
      return { action: "fullscreen" };
    }
    case "downArrow": {
      if (video.muted) {
        return { action: "none" };
      }
      const next = roundedVolume((video.volume ?? 1) - VOLUME_STEP);
      video.volume = next;
      video.muted = next === 0;
      return { action: "volume", volume: next };
    }
    case "upArrow": {
      const next = roundedVolume((video.volume ?? 0) + VOLUME_STEP);
      video.volume = next;
      video.muted = false;
      return { action: "volume", volume: next };
    }
    case "accel-downArrow": {
      video.muted = true;
      return { action: "mute" };
    }
    case "accel-upArrow": {
      video.muted = false;
      return { action: "unmute" };
    }
    case "leftArrow":
    case "accel-leftArrow": {
      if (live) {
        return { action: "none" };
      }
      const delta =
        keystroke === "leftArrow"
          ? SEEK_TIME_SECS
          : (video.duration || 0) / 10;
      video.currentTime = Math.max(0, (video.currentTime || 0) - delta);
      return { action: "seek", currentTime: video.currentTime };
    }
    case "rightArrow":
    case "accel-rightArrow": {
      if (live) {
        return { action: "none" };
      }
      const duration = video.duration || 0;
      const delta =
        keystroke === "rightArrow" ? SEEK_TIME_SECS : duration / 10;
      video.currentTime = Math.min(duration, (video.currentTime || 0) + delta);
      return { action: "seek", currentTime: video.currentTime };
    }
    case "home": {
      if (!live) {
        video.currentTime = 0;
      }
      return { action: "seek", currentTime: video.currentTime };
    }
    case "end": {
      if (!live && Number.isFinite(video.duration)) {
        video.currentTime = video.duration;
      }
      return { action: "seek", currentTime: video.currentTime };
    }
    default:
      return { action: "none" };
  }
}

function handlePlayerKey(video, event, options = {}) {
  const keystroke = buildKeystroke({
    altKey: event.altKey,
    shiftKey: event.shiftKey,
    metaKey: event.metaKey,
    ctrlKey: event.ctrlKey,
    key: event.key,
    platform: options.platform,
  });
  return applyKeystroke(video, keystroke, {
    ...options,
    isFullscreen: options.isFullscreen,
    pauseOnClose: event.shiftKey ? false : options.pauseOnClose,
  });
}

/** Firefox page shortcut: Ctrl+Shift+] (macOS: Cmd+Shift+Option+]). */
function isToggleShortcut(event, platform = "") {
  const mac = isMacPlatform(platform);
  if (event.code !== "BracketRight" && event.key !== "]") {
    return false;
  }
  if (mac) {
    return event.metaKey && event.shiftKey && event.altKey && !event.ctrlKey;
  }
  return event.ctrlKey && event.shiftKey && !event.altKey && !event.metaKey;
}

/* ---- pip/player.js ---- */
const ICONS = {
  close:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M3.2 2.1 8 6.9l4.8-4.8 1.1 1.1L9.1 8l4.8 4.8-1.1 1.1L8 9.1l-4.8 4.8-1.1-1.1L6.9 8 2.1 3.2z"/></svg>',
  unpip:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M2 3.5A1.5 1.5 0 0 1 3.5 2h9A1.5 1.5 0 0 1 14 3.5V7h-1.5V3.5h-9v9H7V14H3.5A1.5 1.5 0 0 1 2 12.5zm7 5A1.5 1.5 0 0 1 10.5 7H14a1.5 1.5 0 0 1 1.5 1.5v4A1.5 1.5 0 0 1 14 14h-3.5A1.5 1.5 0 0 1 9 12.5z"/></svg>',
  play: '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M4 2.5v11l9-5.5z"/></svg>',
  pause:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M3.5 2.5h3v11h-3zm6 0h3v11h-3z"/></svg>',
  back: '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M8.2 3.2 3.4 8l4.8 4.8 1-1L6.4 9H13V7H6.4l2.8-2.8z"/></svg>',
  forward:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M7.8 3.2 12.6 8l-4.8 4.8-1-1L9.6 9H3V7h6.6L6.8 4.2z"/></svg>',
  audio:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M2 6.2h2.4L8 3.5v9L4.4 9.8H2zm8 1.8a2 2 0 0 0-1.2-1.8v3.6A2 2 0 0 0 10 8zm0-3.3A5.2 5.2 0 0 1 13.1 8 5.2 5.2 0 0 1 10 11.3v1.5A6.7 6.7 0 0 0 14.6 8 6.7 6.7 0 0 0 10 3.2z"/></svg>',
  muted:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M2 6.2h2.4L8 3.5v9L4.4 9.8H2zm11.2-2.6 1.1 1.1L12.1 7l2.2 2.3-1.1 1.1L11 8.1l-2.2 2.3-1.1-1.1L9.9 7 7.7 4.7l1.1-1.1L11 5.9z"/></svg>',
  cc: '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M1.5 4h13v8h-13zm2.4 5.7c.5.6 1.2.9 2 .9.7 0 1.2-.2 1.6-.6l.7.8c-.6.6-1.4.9-2.4.9-1.2 0-2.1-.4-2.8-1.2S2.1 8.7 2.1 7.5s.4-2.2 1.1-2.9 1.6-1.1 2.8-1.1c1 0 1.8.3 2.4.9l-.7.8c-.4-.4-.9-.6-1.6-.6-.8 0-1.5.3-2 .9S3.4 6.7 3.4 7.5s.2 1.6.5 2.2zm5.7 0c.5.6 1.2.9 2 .9.7 0 1.2-.2 1.6-.6l.7.8c-.6.6-1.4.9-2.4.9-1.2 0-2.1-.4-2.8-1.2s-1-1.8-1-3s.4-2.2 1.1-2.9 1.6-1.1 2.8-1.1c1 0 1.8.3 2.4.9l-.7.8c-.4-.4-.9-.6-1.6-.6-.8 0-1.5.3-2 .9s-.5 1.4-.5 2.2.2 1.6.5 2.2z"/></svg>',
  speed:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M8 1.5A6.5 6.5 0 1 1 1.5 8 6.5 6.5 0 0 1 8 1.5M8 3a5 5 0 1 0 5 5A5 5 0 0 0 8 3m.8 2v2.4l2 1.2-.8 1.2L7 8.2V5z"/></svg>',
  enterFs:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M3 3h4v1.5H4.5V7H3zm9 0h1v4h-1.5V4.5H9V3zM3 9h1.5v2.5H7V13H3zm8.5 2.5V9H13v4H9v-1.5z"/></svg>',
  exitFs:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M5.5 2.5v3H2.5V4h1.5V2.5zm5 0H13V4h1.5v1.5H10.5zM2.5 10.5h3V13H4v-1.5H2.5zm8 0H13.5V9H12v1.5h-1.5z"/></svg>',
};

Object.assign(ICONS, {
  muted:
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M1.5 6h2.8L8 3v10l-3.7-3H1.5z"/><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" d="m10.5 5.5 4 5m0-5-4 5"/></svg>',
  cc: '<svg viewBox="0 0 16 16" aria-hidden="true"><rect x="1.5" y="3.25" width="13" height="9.5" rx="1.5" fill="none" stroke="currentColor" stroke-width="1.3"/><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.3" d="M6.4 6.5a2 2 0 1 0 0 3m5.4-3a2 2 0 1 0 0 3"/></svg>',
});

function button(id, tooltip, icon, extraClass = "") {
  return `<button type="button" id="${id}" class="control-item control-button ${extraClass}" data-tooltip="${tooltip}">${icon}</button>`;
}

function playerMarkup(strings) {
  return `
    <div class="player-holder">
      <div class="video-stage">
        <video id="pip-video" playsinline disablepictureinpicture></video>
      </div>
      <div id="captions"></div>
      <div id="controls" showing>
        ${button("unpip", strings.unpip, ICONS.unpip)}
        ${button("close", strings.close, ICONS.close)}
        <div id="controls-bottom-gradient" class="control-item"></div>
        <div id="controls-bottom">
          <div class="controls-bottom-upper">
            <div class="scrubber-no-drag">
              <input id="scrubber" class="control-item" type="range" min="0" max="1000" value="0" step="1" />
            </div>
          </div>
          <div class="controls-bottom-lower">
            <div class="start-controls">
              <span id="timestamp" class="control-item">0:00 / 0:00</span>
            </div>
            <div class="center-controls">
              ${button("seekBackward", strings.seekBack, ICONS.back)}
              ${button("playpause", strings.play, ICONS.play)}
              ${button("seekForward", strings.seekForward, ICONS.forward)}
            </div>
            <div class="end-controls">
              ${button("audio", strings.mute, ICONS.audio, "center-tooltip")}
              <input id="audio-scrubber" class="control-item" type="range" min="0" max="1" step="0.01" value="1" />
              ${button("closed-caption", strings.captions, ICONS.cc)}
              ${button("speed", strings.speed, ICONS.speed)}
              ${button("fullscreen", strings.fullscreen, ICONS.enterFs)}
            </div>
          </div>
        </div>
        <div id="cc-settings" class="panel hide">
          <div class="subtitle-grid">
            <span>${strings.subtitles}</span>
            <label class="switch">
              <input id="subtitles-toggle" type="checkbox" checked />
              <span class="slider"></span>
            </label>
          </div>
          <div class="grey-line"></div>
          <h2>${strings.fontSize}</h2>
          <label><input type="radio" name="cc-size" value="small" /> ${strings.small}</label>
          <label><input type="radio" name="cc-size" value="medium" checked /> ${strings.medium}</label>
          <label><input type="radio" name="cc-size" value="large" /> ${strings.large}</label>
        </div>
        <div id="speed-settings" class="panel hide">
          <h2>${strings.speed}</h2>
          ${[0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]
            .map(
              (rate) =>
                `<label><input type="radio" name="speed" value="${rate}" ${
                  rate === 1 ? "checked" : ""
                } /> ${rate === 1 ? strings.normal : `${rate}×`}</label>`
            )
            .join("")}
        </div>
      </div>
    </div>
  `;
}

function localize() {
  const t = (key, fallback) =>
    typeof chrome !== "undefined" && chrome.i18n?.getMessage(key)
      ? chrome.i18n.getMessage(key)
      : fallback;
  return {
    unpip: t("unpipTooltip", "Back to tab"),
    close: t("closeTooltip", "Close (Ctrl+W). Shift+click keeps playing"),
    play: t("playTooltip", "Play (Space)"),
    pause: t("pauseTooltip", "Pause (Space)"),
    seekBack: t("seekBackTooltip", "Back 5 seconds"),
    seekForward: t("seekForwardTooltip", "Forward 5 seconds"),
    mute: t("muteTooltip", "Mute (Ctrl+↓)"),
    unmute: t("unmuteTooltip", "Unmute (Ctrl+↑)"),
    captions: t("captionsTooltip", "Captions"),
    speed: t("speedTooltip", "Playback speed"),
    fullscreen: t("fullscreenTooltip", "Fullscreen (F)"),
    exitFullscreen: t("exitFullscreenTooltip", "Exit fullscreen (F)"),
    subtitles: t("subtitlesLabel", "Subtitles"),
    fontSize: t("fontSizeLabel", "Font size"),
    small: t("fontSmall", "Small"),
    medium: t("fontMedium", "Medium"),
    large: t("fontLarge", "Large"),
    normal: t("speedNormal", "Normal"),
  };
}

class PipPlayer {
  constructor({ sourceVideo, settings, openerWindow, onClose }) {
    this.sourceVideo = sourceVideo;
    this.settings = settings;
    this.openerWindow = openerWindow;
    this.onClose = onClose;
    this.pipWindow = null;
    this.stream = null;
    this.usingNative = false;
    this.maximized = false;
    this.restoreBounds = null;
    this.strings = localize();
    this.captionTimer = 0;
    this.hideTimer = 0;
    this.resizeSnapTimer = 0;
    this.fittingWindow = false;
    this.lastInnerSize = null;
    this.bound = [];
    this.sourceBound = [];
  }

  contentSize() {
    return videoContentSize(this.sourceVideo, this.stream);
  }

  desiredInnerSize() {
    return pipWindowSize(this.sourceVideo, undefined, undefined, this.stream);
  }

  applyVideoAspect() {
    const video = this.pipWindow && !this.pipWindow.closed ? this.qs("pip-video") : null;
    if (!video) {
      return;
    }
    const { width, height, ratio } = this.contentSize();
    if (!ratio) {
      return;
    }
    video.style.aspectRatio = `${width} / ${height}`;
    this.pipWindow.document.documentElement.style.setProperty("--pip-aspect", String(ratio));
  }

  fitPipWindow({ mode = "desired" } = {}) {
    if (!this.pipWindow || this.pipWindow.closed || this.maximized || this.usingNative) {
      return false;
    }
    const { ratio } = this.contentSize();
    const win = this.pipWindow;
    const innerWidth = Number(win.innerWidth) || 0;
    const innerHeight = Number(win.innerHeight) || 0;
    if (!innerWidth || !innerHeight) {
      return false;
    }

    let next;
    if (mode === "snap") {
      next = snapInnerToAspect(innerWidth, innerHeight, ratio, this.lastInnerSize);
    } else if (mode === "grow") {
      next = growInnerToAspect(innerWidth, innerHeight, ratio);
    } else {
      next = this.desiredInnerSize();
    }

    if (!aspectMismatch(innerWidth, innerHeight, ratio)) {
      this.lastInnerSize = { width: innerWidth, height: innerHeight };
      return false;
    }

    const outer = outerSizeForInner(win, next.width, next.height);
    this.fittingWindow = true;
    try {
      win.resizeTo(outer.width, outer.height);
      this.lastInnerSize = {
        width: Number(win.innerWidth) || next.width,
        height: Number(win.innerHeight) || next.height,
      };
      return true;
    } catch {
      this.lastInnerSize = { width: innerWidth, height: innerHeight };
      return false;
    } finally {
      const clear = () => {
        this.fittingWindow = false;
      };
      if (typeof win.setTimeout === "function") {
        win.setTimeout(clear, 0);
      } else {
        clear();
      }
    }
  }

  scheduleAspectSnap() {
    if (this.fittingWindow || this.maximized || !this.pipWindow) {
      return;
    }
    if (this.resizeSnapTimer) {
      this.openerWindow.clearTimeout(this.resizeSnapTimer);
    }
    this.resizeSnapTimer = this.openerWindow.setTimeout(() => {
      this.resizeSnapTimer = 0;
      this.fitPipWindow({ mode: "snap" });
    }, 120);
  }

  stillOpen() {
    return !this._tornDown;
  }

  abandonOpen() {
    this.stopStream();
    if (this.pipWindow && !this.pipWindow.closed) {
      this.pipWindow.close();
    }
    this.pipWindow = null;
    return { mode: "aborted" };
  }

  async open() {
    if (this._tornDown) {
      return this.abandonOpen();
    }
    if (!("documentPictureInPicture" in window)) {
      return this.openNative();
    }
    try {
      this.stream = this.sourceVideo.captureStream();
    } catch {
      return this.openNative();
    }
    const existing = window.documentPictureInPicture.window;
    if (existing && !existing.closed) {
      this.pipWindow = existing;
    } else {
      try {
        this.pipWindow = await window.documentPictureInPicture.requestWindow(
          pipRequestOptions(this.sourceVideo, this.stream)
        );
      } catch {
        if (!this.stillOpen()) {
          return this.abandonOpen();
        }
        this.stopStream();
        return this.openNative();
      }
    }
    if (!this.stillOpen()) {
      return this.abandonOpen();
    }

    this.installDocument(this.pipWindow);
    const pipVideo = this.pipWindow.document.getElementById("pip-video");
    try {
      pipVideo.srcObject = this.stream;
      pipVideo.muted = true;
      pipVideo.play().catch(() => {});
    } catch {
      if (this.pipWindow && !this.pipWindow.closed) {
        this.pipWindow.close();
      }
      this.pipWindow = null;
      this.stopStream();
      if (!this.stillOpen()) {
        return this.abandonOpen();
      }
      return this.openNative();
    }
    if (!this.stillOpen()) {
      return this.abandonOpen();
    }

    this.bindSource();
    this.bindControls();
    this.sync();
    this.applyVideoAspect();
    this.revealControls(true);
    this.fitPipWindow({ mode: "grow" });
    return { mode: "document", window: this.pipWindow };
  }

  async openNative() {
    if (!this.stillOpen()) {
      return this.abandonOpen();
    }
    if (!this.sourceVideo.requestPictureInPicture) {
      throw new Error("Picture-in-Picture is not available");
    }
    await this.sourceVideo.requestPictureInPicture();
    if (!this.stillOpen()) {
      document.exitPictureInPicture?.();
      return this.abandonOpen();
    }
    this.usingNative = true;
    this.bindNativeLeave();
    return { mode: "video" };
  }

  bindNativeLeave() {
    this.listenSource(
      this.sourceVideo,
      "leavepictureinpicture",
      () => this.teardown({ pause: this._pendingPause ?? this.settings.pauseOnClose })
    );
  }

  async replaceSource(video) {
    if (!this.stillOpen() || !video) {
      return { ok: false };
    }
    this.unbindSource();
    this.stopStream();
    this.sourceVideo = video;
    if (this.usingNative) {
      await video.requestPictureInPicture();
      if (!this.stillOpen()) {
        return { ok: false };
      }
      this.bindNativeLeave();
      return { ok: true, mode: "video" };
    }
    const pipVideo = this.qs("pip-video");
    this.stream = video.captureStream();
    pipVideo.srcObject = this.stream;
    pipVideo.muted = true;
    await pipVideo.play().catch(() => {});
    if (!this.stillOpen()) {
      return { ok: false };
    }
    this.bindSource();
    this.sync();
    this.applyVideoAspect();
    this.fitPipWindow({ mode: "desired" });
    return { ok: true, mode: "document" };
  }

  installDocument(pipWindow) {
    const doc = pipWindow.document;
    doc.head.replaceChildren();
    doc.body.replaceChildren();
    doc.documentElement.lang = document.documentElement.lang || "en";
    doc.title = this.sourceVideo.title || document.title || "Picture-in-Picture";
    const style = doc.createElement("link");
    style.rel = "stylesheet";
    style.href = chrome.runtime.getURL("pip/player.css");
    doc.head.append(style);
    doc.body.innerHTML = playerMarkup(this.strings);
    if (isMacPlatform(navigator.platform)) {
      doc.body.classList.add("mac");
    }
    this.applyCaptionSize(this.settings.captionFontSize);
  }

  qs(id) {
    return this.pipWindow.document.getElementById(id);
  }

  listenSource(target, type, handler, options) {
    if (!target) {
      return;
    }
    target.addEventListener(type, handler, options);
    this.sourceBound.push(() => target.removeEventListener(type, handler, options));
  }

  unbindSource() {
    for (const unbind of this.sourceBound) {
      unbind();
    }
    this.sourceBound = [];
  }

  bindSource() {
    const events = ["play", "pause", "ended", "timeupdate", "volumechange", "ratechange", "durationchange"];
    for (const type of events) {
      this.listenSource(this.sourceVideo, type, () => this.sync());
    }
    this.listenSource(this.sourceVideo, "loadedmetadata", () => {
      this.sync();
      this.applyVideoAspect();
      this.fitPipWindow({ mode: "desired" });
    });
    this.listenSource(this.sourceVideo, "resize", () => {
      this.applyVideoAspect();
      this.fitPipWindow({ mode: "desired" });
    });
    this.listenSource(this.sourceVideo, "emptied", () => this.close({ pause: false, reason: "emptied" }));
    const track = this.stream?.getVideoTracks?.()[0];
    if (track?.addEventListener) {
      const onTrackResize = () => this.fitPipWindow({ mode: "desired" });
      track.addEventListener("resize", onTrackResize);
      this.sourceBound.push(() => track.removeEventListener("resize", onTrackResize));
    }
  }

  bindControls() {
    const doc = this.pipWindow.document;
    const controls = this.qs("controls");
    this.listen(this.qs("close"), "click", (event) => {
      this.close({ pause: event.shiftKey ? false : this.settings.pauseOnClose, reason: "close" });
    });
    this.listen(this.qs("unpip"), "click", () => {
      this.openerWindow.focus();
      this.close({ pause: false, reason: "unpip" });
    });
    this.listen(this.qs("playpause"), "click", () => this.togglePlay());
    this.listen(this.qs("seekBackward"), "click", () => this.seekBy(-SEEK_TIME_SECS));
    this.listen(this.qs("seekForward"), "click", () => this.seekBy(SEEK_TIME_SECS));
    this.listen(this.qs("audio"), "click", () => this.toggleMute());
    this.listen(this.qs("fullscreen"), "click", () => this.toggleFullscreen());
    this.listen(this.qs("closed-caption"), "click", () => this.togglePanel("cc-settings"));
    this.listen(this.qs("speed"), "click", () => this.togglePanel("speed-settings"));
    this.listen(this.qs("scrubber"), "input", (event) => {
      if (isLiveStream(this.sourceVideo)) {
        return;
      }
      const duration = this.sourceVideo.duration || 0;
      this.sourceVideo.currentTime = (Number(event.target.value) / 1000) * duration;
    });
    this.listen(this.qs("audio-scrubber"), "input", (event) => {
      const volume = Number(event.target.value);
      this.sourceVideo.volume = volume;
      this.sourceVideo.muted = volume === 0;
    });
    this.listen(this.qs("subtitles-toggle"), "change", (event) => {
      this.settings.captionsEnabled = event.target.checked;
      this.updateCaptions();
    });
    for (const radio of doc.querySelectorAll('input[name="cc-size"]')) {
      this.listen(radio, "change", () => {
        if (radio.checked) {
          this.settings.captionFontSize = radio.value;
          this.applyCaptionSize(radio.value);
        }
      });
    }
    for (const radio of doc.querySelectorAll('input[name="speed"]')) {
      this.listen(radio, "change", () => {
        if (radio.checked) {
          this.sourceVideo.playbackRate = Number(radio.value);
        }
      });
    }
    this.listen(controls, "dblclick", (event) => {
      if (event.target.id === "controls") {
        this.toggleFullscreen();
      }
    });
    this.listen(doc, "keydown", (event) => this.onKeyDown(event));
    this.listen(this.pipWindow, "pagehide", () =>
      this.teardown({ pause: this._pendingPause ?? this.settings.pauseOnClose })
    );
    this.listen(this.pipWindow, "resize", () => this.scheduleAspectSnap());
    this.listen(controls, "mousemove", () => this.revealControls(false));
    this.listen(controls, "mouseenter", () => this.showControls());
    this.listen(controls, "mouseleave", () => {
      if (!controls.hasAttribute("keying") && !controls.hasAttribute("donthide")) {
        this.hideControls();
      }
    });
    this.captionTimer = this.openerWindow.setInterval(() => this.updateCaptions(), 250);
  }

  listen(target, type, handler, options) {
    if (!target) {
      return;
    }
    target.addEventListener(type, handler, options);
    this.bound.push(() => target.removeEventListener(type, handler, options));
  }

  onKeyDown(event) {
    if (!this.settings.keyboardControlsEnabled) {
      return;
    }
    const controls = this.qs("controls");
    if (event.key === "Tab") {
      controls?.setAttribute("keying", "");
      this.showControls();
    }
    if (event.key === "Escape" && this.qs("cc-settings") && !this.qs("cc-settings").classList.contains("hide")) {
      this.hidePanels();
      event.preventDefault();
      return;
    }
    const result = handlePlayerKey(this.sourceVideo, event, {
      platform: navigator.platform,
      isLive: isLiveStream(this.sourceVideo),
      isFullscreen: this.maximized,
      pauseOnClose: this.settings.pauseOnClose,
    });
    if (result.action === "none") {
      return;
    }
    event.preventDefault();
    if (result.action === "close") {
      this.close({ pause: result.pause, reason: "shortcut" });
      return;
    }
    if (result.action === "fullscreen" || result.action === "exit-fullscreen") {
      this.toggleFullscreen();
    }
    this.sync();
  }

  togglePlay() {
    if (this.sourceVideo.paused || this.sourceVideo.ended) {
      this.sourceVideo.play()?.catch(() => {});
    } else {
      this.sourceVideo.pause();
    }
  }

  seekBy(delta) {
    if (isLiveStream(this.sourceVideo)) {
      return;
    }
    const duration = this.sourceVideo.duration || 0;
    this.sourceVideo.currentTime = Math.min(
      duration,
      Math.max(0, (this.sourceVideo.currentTime || 0) + delta)
    );
  }

  toggleMute() {
    this.sourceVideo.muted = !this.sourceVideo.muted;
    if (!this.sourceVideo.muted && this.sourceVideo.volume === 0) {
      this.sourceVideo.volume = 1;
    }
  }

  toggleFullscreen() {
    if (!this.pipWindow) {
      return;
    }
    if (this.maximized) {
      const bounds = this.restoreBounds;
      this.maximized = false;
      if (bounds) {
        this.pipWindow.resizeTo(bounds.width, bounds.height);
      }
      this.qs("fullscreen").innerHTML = ICONS.enterFs;
      this.qs("fullscreen").dataset.tooltip = this.strings.fullscreen;
      return;
    }
    this.restoreBounds = {
      width: this.pipWindow.outerWidth,
      height: this.pipWindow.outerHeight,
    };
    this.maximized = true;
    this.pipWindow.resizeTo(
      this.pipWindow.screen.availWidth,
      this.pipWindow.screen.availHeight
    );
    this.qs("fullscreen").innerHTML = ICONS.exitFs;
    this.qs("fullscreen").dataset.tooltip = this.strings.exitFullscreen;
  }

  togglePanel(id) {
    const panel = this.qs(id);
    const other = id === "cc-settings" ? this.qs("speed-settings") : this.qs("cc-settings");
    other?.classList.add("hide");
    const hidden = panel.classList.contains("hide");
    panel.classList.toggle("hide", !hidden);
    const controls = this.qs("controls");
    if (hidden) {
      controls.setAttribute("donthide", "");
      this.showControls();
    } else {
      controls.removeAttribute("donthide");
    }
  }

  hidePanels() {
    this.qs("cc-settings")?.classList.add("hide");
    this.qs("speed-settings")?.classList.add("hide");
    this.qs("controls")?.removeAttribute("donthide");
  }

  applyCaptionSize(size) {
    this.pipWindow?.document.documentElement.style.setProperty(
      "--caption-scale",
      String(captionFontScale(size))
    );
    const radio = this.pipWindow?.document.querySelector(`input[name="cc-size"][value="${size}"]`);
    if (radio) {
      radio.checked = true;
    }
  }

  updateCaptions() {
    const box = this.qs("captions");
    if (!box) {
      return;
    }
    if (!this.settings.captionsEnabled || !this.qs("subtitles-toggle")?.checked) {
      box.textContent = "";
      return;
    }
    box.textContent = showingCaptionText(this.sourceVideo) || pageCaptionText(this.openerWindow.document);
  }

  sync() {
    if (!this.pipWindow || this.pipWindow.closed) {
      return;
    }
    const playing = !this.sourceVideo.paused && !this.sourceVideo.ended;
    this.qs("playpause").innerHTML = playing ? ICONS.pause : ICONS.play;
    this.qs("playpause").dataset.tooltip = playing ? this.strings.pause : this.strings.play;
    this.qs("audio").innerHTML = this.sourceVideo.muted || this.sourceVideo.volume === 0 ? ICONS.muted : ICONS.audio;
    this.qs("audio").dataset.tooltip =
      this.sourceVideo.muted || this.sourceVideo.volume === 0 ? this.strings.unmute : this.strings.mute;
    this.qs("timestamp").textContent = formatTimestamp(
      this.sourceVideo.currentTime,
      this.sourceVideo.duration
    );
    if (!isLiveStream(this.sourceVideo)) {
      this.qs("scrubber").value = String(
        Math.round(progressRatio(this.sourceVideo.currentTime, this.sourceVideo.duration) * 1000)
      );
    }
    this.qs("audio-scrubber").value = String(this.sourceVideo.muted ? 0 : this.sourceVideo.volume);
    const speedRadio = this.pipWindow.document.querySelector(
      `input[name="speed"][value="${this.sourceVideo.playbackRate}"]`
    );
    if (speedRadio) {
      speedRadio.checked = true;
    }
    const live = isLiveStream(this.sourceVideo);
    this.qs("seekBackward").disabled = live;
    this.qs("seekForward").disabled = live;
    this.qs("scrubber").disabled = live;
    if (!playing) {
      this.revealControls(true);
    }
    this.updateCaptions();
  }

  revealControls(keep) {
    const controls = this.qs("controls");
    if (!controls) {
      return;
    }
    controls.setAttribute("showing", "");
    this.showControls();
    if (this.hideTimer) {
      this.openerWindow.clearTimeout(this.hideTimer);
    }
    if (!keep) {
      this.hideTimer = this.openerWindow.setTimeout(() => {
        controls.removeAttribute("showing");
        if (!controls.hasAttribute("keying") && !controls.hasAttribute("donthide")) {
          this.hideControls();
        }
      }, 3000);
    }
  }

  showControls() {
    const controls = this.qs("controls");
    controls?.setAttribute("showing", "");
  }

  hideControls() {
    const controls = this.qs("controls");
    if (this.sourceVideo.paused) {
      return;
    }
    controls?.removeAttribute("showing");
  }

  stopStream() {
    if (!this.stream) {
      return;
    }
    for (const track of this.stream.getTracks()) {
      track.stop();
    }
    this.stream = null;
  }

  close({ pause = false, reason = "close" } = {}) {
    this._pendingPause = pause;
    if (this.usingNative && document.pictureInPictureElement) {
      document.exitPictureInPicture?.();
    }
    if (this.pipWindow && !this.pipWindow.closed) {
      this.pipWindow.close();
    }
    this.teardown({ pause, reason });
  }

  teardown({ pause = false } = {}) {
    if (this._tornDown) {
      return;
    }
    this._tornDown = true;
    for (const unbind of this.bound) {
      unbind();
    }
    this.bound = [];
    this.unbindSource();
    if (this.captionTimer) {
      this.openerWindow.clearInterval(this.captionTimer);
    }
    if (this.hideTimer) {
      this.openerWindow.clearTimeout(this.hideTimer);
    }
    if (this.resizeSnapTimer) {
      this.openerWindow.clearTimeout(this.resizeSnapTimer);
      this.resizeSnapTimer = 0;
    }
    this.stopStream();
    if (pause) {
      this.sourceVideo.pause();
    }
    this.onClose?.({ pause });
  }
}

/* ---- content/content.js ---- */
const TOGGLE_ID = "pip-addon-toggle";
const PLACEHOLDER_ID = "pip-addon-placeholder";
const SAMPLE_MS = 80;

function isDocumentPipWindow() {
  if (window.matchMedia("(display-mode: picture-in-picture)").matches) {
    return true;
  }
  try {
    return window.opener?.documentPictureInPicture?.window === window;
  } catch {
    return false;
  }
}

const IS_DOCUMENT_PIP = isDocumentPipWindow();

let settings = { ...DEFAULT_SETTINGS };
loadSettings().then((next) => {
  settings = next;
});
let player = null;
let activeVideo = null;
let hoveredVideo = null;
let lastMouse = { x: 0, y: 0, present: false };
let sampleTimer = 0;
let autoOpened = false;

const videos = new Set();
const videoIds = new WeakMap();
let videoSeq = 0;
let mutationTimer = 0;
let remoteSource = null;
let remoteReceiver = null;

function viewport() {
  return { width: window.innerWidth, height: window.innerHeight };
}

function allVideos() {
  const next = collectVideos(document, []);
  videos.clear();
  for (const video of next) {
    if (!videoIds.has(video)) {
      videoIds.set(video, `pip-${++videoSeq}`);
    }
    videos.add(video);
  }
  return [...videos];
}

function eligibleVideos() {
  return allVideos().filter((video) =>
    shouldShowPictureInPictureToggle(video, settings, {
      videoWidth: video.clientWidth,
      videoHeight: video.clientHeight,
    })
  );
}

function videoFromPoint(x, y) {
  const stack = document.elementsFromPoint(x, y);
  for (const node of stack) {
    if (node.id === TOGGLE_ID || node.id === `${TOGGLE_ID}-host`) {
      return hoveredVideo;
    }
    if (node.tagName === "VIDEO") {
      return node;
    }
  }
  let match = null;
  let matchArea = 0;
  for (const video of allVideos()) {
    const rect = video.getBoundingClientRect();
    if (x >= rect.left && x <= rect.right && y >= rect.top && y <= rect.bottom) {
      const area = rect.width * rect.height;
      if (area > matchArea) {
        match = video;
        matchArea = area;
      }
    }
  }
  return match;
}

function ensureToggle() {
  let host = document.getElementById(`${TOGGLE_ID}-host`);
  if (host) {
    return host;
  }
  host = document.createElement("div");
  host.id = `${TOGGLE_ID}-host`;
  host.setAttribute("data-pip-addon", "toggle");
  const shadow = host.attachShadow({ mode: "closed" });
  const style = document.createElement("style");
  style.textContent = `
    :host { all: initial; }
    #wrap {
      position: fixed;
      z-index: 2147483646;
      pointer-events: none;
    }
    button {
      pointer-events: auto;
      display: flex;
      align-items: center;
      gap: 8px;
      height: 32px;
      padding: 0 10px;
      border: 0;
      border-radius: 4px;
      background: rgb(12 12 13 / 80%);
      color: #fff;
      font: 12px/1 system-ui, sans-serif;
      cursor: pointer;
      opacity: 0;
      transform: translateY(-4px);
      transition: opacity 160ms ease, transform 160ms ease, background 160ms ease;
    }
    #wrap.visible button { opacity: 1; transform: none; }
    button:hover { background: rgb(12 12 13 / 95%); }
    svg { width: 16px; height: 16px; fill: #fff; }
  `;
  const wrap = document.createElement("div");
  wrap.id = "wrap";
  const button = document.createElement("button");
  button.id = TOGGLE_ID;
  button.type = "button";
  button.setAttribute(
    "aria-label",
    chrome.i18n?.getMessage("toggleLabel") || "Watch in Picture-in-Picture"
  );
  button.innerHTML = `
    <svg viewBox="0 0 16 16" aria-hidden="true"><path d="M2 3.5A1.5 1.5 0 0 1 3.5 2h9A1.5 1.5 0 0 1 14 3.5v9a1.5 1.5 0 0 1-1.5 1.5H8V12h4.5v-9h-9V7H2z"/><path d="M2 8.5A1.5 1.5 0 0 1 3.5 7H8a1.5 1.5 0 0 1 1.5 1.5v4A1.5 1.5 0 0 1 8 14H3.5A1.5 1.5 0 0 1 2 12.5z"/></svg>
    <span>${chrome.i18n?.getMessage("toggleShort") || "Picture-in-Picture"}</span>
  `;
  const stop = (event) => {
    event.preventDefault();
    event.stopPropagation();
  };
  for (const type of ["pointerdown", "mousedown", "mouseup", "auxclick"]) {
    button.addEventListener(type, stop, true);
  }
  button.addEventListener(
    "click",
    (event) => {
      stop(event);
      if (hoveredVideo) {
        toggleVideo(hoveredVideo);
      }
    },
    true
  );
  wrap.append(button);
  shadow.append(style, wrap);
  document.documentElement.append(host);
  host._wrap = wrap;
  host._shadow = shadow;
  return host;
}

function positionToggle(video) {
  const host = ensureToggle();
  const wrap = host._wrap;
  if (!video || !settings.toggleEnabled) {
    wrap.classList.remove("visible");
    return;
  }
  const eligible = shouldShowPictureInPictureToggle(video, settings, {
    videoWidth: video.clientWidth,
    videoHeight: video.clientHeight,
  });
  if (!eligible) {
    wrap.classList.remove("visible");
    return;
  }
  const rect = video.getBoundingClientRect();
  wrap.style.top = `${Math.max(8, rect.top + 10)}px`;
  wrap.style.left = `${Math.max(8, rect.right - 170)}px`;
  wrap.classList.add("visible");
}

function sampleMouse() {
  if (!lastMouse.present || !settings.toggleEnabled) {
    ensureToggle()._wrap.classList.remove("visible");
    return;
  }
  hoveredVideo = videoFromPoint(lastMouse.x, lastMouse.y);
  positionToggle(hoveredVideo);
}

function startSampling() {
  if (IS_DOCUMENT_PIP || sampleTimer) {
    return;
  }
  sampleTimer = window.setInterval(sampleMouse, SAMPLE_MS);
}

function stopSampling() {
  window.clearInterval(sampleTimer);
  sampleTimer = 0;
}

function showPlaceholder(video) {
  hidePlaceholder();
  if (!settings.showPlaceholder) {
    return;
  }
  const host = document.createElement("div");
  host.id = PLACEHOLDER_ID;
  host.style.cssText = "position:fixed;z-index:2147483645;pointer-events:none;";
  const shadow = host.attachShadow({ mode: "closed" });
  const box = document.createElement("div");
  box.style.cssText = `
    display:flex;align-items:center;justify-content:center;flex-direction:column;gap:10px;
    background:#0c0c0d;color:#fff;font:14px/1.4 system-ui,sans-serif;text-align:center;padding:16px;
  `;
  box.innerHTML = `<div>${
    chrome.i18n?.getMessage("placeholderText") || "This video is playing in Picture-in-Picture"
  }</div>`;
  const button = document.createElement("button");
  button.textContent = chrome.i18n?.getMessage("placeholderReturn") || "Return this tab";
  button.style.cssText =
    "pointer-events:auto;background:#0060df;color:#fff;border:0;border-radius:4px;padding:8px 12px;cursor:pointer;";
  button.addEventListener("click", (event) => {
    event.preventDefault();
    event.stopPropagation();
    player?.close({ pause: false, reason: "placeholder" });
  });
  box.append(button);
  shadow.append(box);
  document.documentElement.append(host);
  const place = () => {
    const rect = video.getBoundingClientRect();
    host.style.top = `${rect.top}px`;
    host.style.left = `${rect.left}px`;
    box.style.width = `${rect.width}px`;
    box.style.height = `${rect.height}px`;
  };
  place();
  host._place = place;
}

function hidePlaceholder() {
  document.getElementById(PLACEHOLDER_ID)?.remove();
}

function waitForIceGathering(connection) {
  if (connection.iceGatheringState === "complete") {
    return Promise.resolve();
  }
  return new Promise((resolve) => {
    const done = () => {
      if (connection.iceGatheringState !== "complete") {
        return;
      }
      window.clearTimeout(timer);
      connection.removeEventListener("icegatheringstatechange", done);
      resolve();
    };
    const timer = window.setTimeout(() => {
      connection.removeEventListener("icegatheringstatechange", done);
      resolve();
    }, 1500);
    connection.addEventListener("icegatheringstatechange", done);
  });
}

function relayRemote(targetFrameId, event, sessionId, payload) {
  return chrome.runtime
    .sendMessage({
      type: "PIP_REMOTE_RELAY",
      targetFrameId,
      event,
      sessionId,
      payload,
    })
    .catch(() => null);
}

function cleanupRemoteSource({ pause = false, notify = true } = {}) {
  const session = remoteSource;
  if (!session) {
    return;
  }
  remoteSource = null;
  window.clearInterval(session.stateTimer);
  session.connection.close();
  for (const track of session.stream.getTracks()) {
    track.stop();
  }
  if (pause) {
    session.video.pause();
  }
  if (notify) {
    relayRemote(0, "close", session.sessionId);
  }
  if (player === session.controller) {
    player = null;
    activeVideo = null;
    autoOpened = false;
    hidePlaceholder();
  }
}

function applyRemoteCommand(video, command) {
  if (!video || !command) {
    return;
  }
  switch (command.name) {
    case "play":
      video.play()?.catch(() => {});
      break;
    case "pause":
      video.pause();
      break;
    case "currentTime":
      video.currentTime = Number(command.value) || 0;
      break;
    case "volume":
      video.volume = Number(command.value);
      break;
    case "muted":
      video.muted = Boolean(command.value);
      break;
    case "playbackRate":
      video.playbackRate = Number(command.value) || 1;
      break;
  }
}

async function openRemoteSource(video) {
  const stream = video.captureStream();
  const tracks = stream.getVideoTracks();
  if (!tracks.length) {
    for (const track of stream.getTracks()) {
      track.stop();
    }
    throw new Error("The captured video stream has no video track");
  }

  const sessionId = crypto.randomUUID();
  const connection = new RTCPeerConnection({ iceServers: [] });
  for (const track of tracks) {
    const sender = connection.addTrack(track, stream);
    await preserveVideoQuality(track, sender).catch(() => {});
  }

  try {
    await connection.setLocalDescription(await connection.createOffer());
    await waitForIceGathering(connection);
    const response = await chrome.runtime.sendMessage({
      type: "PIP_REMOTE_OPEN",
      sessionId,
      offer: connection.localDescription.toJSON(),
      state: snapshotVideo(video, document.title),
    });
    if (!response?.ok || !response.answer) {
      throw new Error(response?.reason || "The top frame could not open Document PiP");
    }
    await connection.setRemoteDescription(response.answer);

    const controller = {
      stillOpen: () => remoteSource?.sessionId === sessionId,
      close: ({ pause = false } = {}) => cleanupRemoteSource({ pause }),
    };
    const sendState = () =>
      relayRemote(0, "state", sessionId, snapshotVideo(video, document.title));
    const stateTimer = window.setInterval(sendState, 250);
    remoteSource = { sessionId, video, stream, connection, controller, stateTimer };
    connection.addEventListener("connectionstatechange", () => {
      if (connection.connectionState === "failed") {
        cleanupRemoteSource();
      }
    });
    player = controller;
    activeVideo = video;
    showPlaceholder(video);
    sendState();
    return { ok: true, mode: "document" };
  } catch (error) {
    relayRemote(0, "close", sessionId);
    connection.close();
    for (const track of stream.getTracks()) {
      track.stop();
    }
    throw error;
  }
}

async function openRemoteReceiver(message) {
  if (window !== window.top || !("documentPictureInPicture" in window)) {
    return { ok: false, reason: "Document PiP is unavailable in the top frame" };
  }
  if (remoteReceiver) {
    remoteReceiver.player.close({ pause: false, reason: "replace-remote" });
  } else if (player) {
    player.close({ pause: false, reason: "replace-remote" });
  }

  let pipWindow = null;
  let connection = null;
  try {
    pipWindow = await window.documentPictureInPicture.requestWindow(pipRequestOptions(message.state));
    connection = new RTCPeerConnection({ iceServers: [] });
    const stream = new MediaStream();
    connection.addEventListener("track", (event) => {
      if (!stream.getTracks().includes(event.track)) {
        stream.addTrack(event.track);
      }
    });
    await connection.setRemoteDescription(message.offer);
    await connection.setLocalDescription(await connection.createAnswer());
    await waitForIceGathering(connection);

    const proxy = new RemoteVideo(stream, message.state, (command) =>
      relayRemote(message.sourceFrameId, "control", message.sessionId, command)
    );
    let session = null;
    const next = new PipPlayer({
      sourceVideo: proxy,
      settings,
      openerWindow: window,
      onClose: ({ pause } = {}) => {
        if (remoteReceiver === session) {
          remoteReceiver = null;
          connection.close();
          relayRemote(message.sourceFrameId, "closed", message.sessionId, { pause });
        }
        if (player === next) {
          player = null;
          activeVideo = null;
          autoOpened = false;
        }
      },
    });
    session = {
      sessionId: message.sessionId,
      sourceFrameId: message.sourceFrameId,
      connection,
      proxy,
      player: next,
    };
    remoteReceiver = session;
    player = next;
    activeVideo = proxy;
    connection.addEventListener("connectionstatechange", () => {
      if (connection.connectionState === "failed" && remoteReceiver === session) {
        next.close({ pause: false, reason: "remote-failed" });
      }
    });
    await next.open();
    return { ok: true, answer: connection.localDescription.toJSON() };
  } catch (error) {
    connection?.close();
    if (pipWindow && !pipWindow.closed) {
      pipWindow.close();
    }
    remoteReceiver = null;
    return { ok: false, reason: String(error?.message || error) };
  }
}

function attachPlayer(nextPlayer, video) {
  player = nextPlayer;
  activeVideo = video;
  showPlaceholder(video);
}

async function toggleVideo(video) {
  if (IS_DOCUMENT_PIP) {
    return { ok: false, reason: "pip-window" };
  }
  if (!video) {
    return { ok: false, reason: "no-video" };
  }
  if (player && activeVideo === video) {
    player.close({ pause: settings.pauseOnClose, reason: "toggle" });
    return { ok: true, closed: true };
  }
  if (settings.respectDisablePictureInPicture && video.disablePictureInPicture) {
    return { ok: false, reason: "disabled" };
  }
  if (window !== window.top) {
    cleanupRemoteSource();
    try {
      return await openRemoteSource(video);
    } catch (error) {
      console.warn("[PiP addon] Cross-frame Document PiP failed; using native PiP.", error);
      /* Fall through to native PiP when the media stream cannot be bridged. */
    }
  }
  if (player && player.stillOpen()) {
    try {
      await player.replaceSource(video);
      if (!player?.stillOpen()) {
        return { ok: false, reason: "aborted" };
      }
      attachPlayer(player, video);
      return { ok: true, replaced: true };
    } catch (error) {
      player.close({ pause: false, reason: "replace-failed" });
      return { ok: false, reason: String(error?.message || error) };
    }
  }
  try {
    const next = new PipPlayer({
      sourceVideo: video,
      settings,
      openerWindow: window,
      onClose: (closed) => {
        if (player === next) {
          player = null;
          activeVideo = null;
          autoOpened = false;
          hidePlaceholder();
        }
        return closed;
      },
    });
    player = next;
    const opened = await next.open();
    if (opened?.mode === "aborted" || !next.stillOpen()) {
      if (player === next) {
        player = null;
        activeVideo = null;
      }
      return { ok: false, reason: "aborted" };
    }
    attachPlayer(next, video);
    return { ok: true, mode: opened?.mode };
  } catch (error) {
    if (player && !player.stillOpen()) {
      player = null;
      activeVideo = null;
    }
    return { ok: false, reason: String(error?.message || error) };
  }
}

function toggleBest() {
  const video = pickBestVideo(allVideos(), viewport());
  if (!video) {
    return Promise.resolve({ ok: false, reason: "no-video" });
  }
  const score = scoreVideo(video, viewport());
  if (window !== window.top && score < 1_000_000) {
    return Promise.resolve({ ok: false, reason: "not-preferred" });
  }
  return toggleVideo(video);
}

function getBestVideoScore() {
  const video = pickBestVideo(allVideos(), viewport());
  if (!video) {
    return null;
  }
  return { score: scoreVideo(video, viewport()) };
}

function registerAutoPip() {
  if (IS_DOCUMENT_PIP) {
    return;
  }
  try {
    navigator.mediaSession.setActionHandler("enterpictureinpicture", async () => {
      if (!settings.autoPipOnTabSwitch || player) {
        return;
      }
      const video = pickBestVideo(
        allVideos().filter((item) => !item.paused && !item.ended),
        viewport()
      );
      if (!video) {
        return;
      }
      const result = await toggleVideo(video);
      autoOpened = Boolean(result?.ok && !result.closed);
    });
  } catch {
    /* Media Session action not supported */
  }
}

function maybeCloseAutoPip() {
  if (autoOpened && player && !document.hidden) {
    player.close({ pause: false, reason: "foregrounded" });
  }
}

document.addEventListener(
  "mousemove",
  (event) => {
    lastMouse = { x: event.clientX, y: event.clientY, present: true };
    startSampling();
  },
  { passive: true }
);

document.addEventListener("mouseout", (event) => {
  if (!event.relatedTarget) {
    lastMouse.present = false;
  }
});

document.addEventListener(
  "keydown",
  (event) => {
    if (!isToggleShortcut(event, navigator.platform)) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    toggleBest();
  },
  true
);

document.addEventListener("visibilitychange", maybeCloseAutoPip);

chrome.storage.onChanged.addListener((changes, area) => {
  if (area !== "sync" || !changes.pipAddonSettings) {
    return;
  }
  settings = mergeSettings(changes.pipAddonSettings.newValue);
  registerAutoPip();
});

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message?.type === "PIP_REMOTE_OPEN" && window === window.top) {
    openRemoteReceiver(message).then(sendResponse);
    return true;
  }
  if (message?.type === "PIP_REMOTE_RELAY") {
    if (message.event === "state" && remoteReceiver?.sessionId === message.sessionId) {
      remoteReceiver.proxy.update(message.payload);
    } else if (message.event === "control" && remoteSource?.sessionId === message.sessionId) {
      applyRemoteCommand(remoteSource.video, message.payload);
    } else if (message.event === "close" && remoteReceiver?.sessionId === message.sessionId) {
      remoteReceiver.player.close({ pause: false, reason: "source-closed" });
    } else if (message.event === "closed" && remoteSource?.sessionId === message.sessionId) {
      cleanupRemoteSource({
        notify: false,
        pause: Boolean(message.payload?.pause),
      });
    }
    sendResponse({ ok: true });
    return;
  }
  if (message?.type === "QUERY_VIDEOS") {
    sendResponse(getBestVideoScore());
    return;
  }
  if (message?.type === "TOGGLE_PIP") {
    toggleBest().then(sendResponse);
    return true;
  }
  if (message?.type === "OPEN_PIP") {
    const video =
      allVideos().find((item) => videoIds.get(item) === message.videoId) ||
      pickBestVideo(allVideos(), viewport());
    toggleVideo(video).then(sendResponse);
    return true;
  }
  if (message?.type === "CLOSE_PIP") {
    player?.close({ pause: message.pause !== false, reason: "message" });
    sendResponse({ ok: true });
  }
});

const observer = new MutationObserver(() => {
  window.clearTimeout(mutationTimer);
  mutationTimer = window.setTimeout(() => {
    allVideos();
    document.getElementById(PLACEHOLDER_ID)?._place?.();
  }, 120);
});
observer.observe(document.documentElement, { childList: true, subtree: true });

registerAutoPip();
allVideos();

globalThis.PipAddonContent = {
  toggleBest,
  toggleVideo,
  getBestVideoScore,
  eligibleVideos,
};
})();
